name: Build addon, run tests and package

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build addon
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Build addon
        run: make build-addon

      - name: Get minimal Node.js version from package.json (Linux & macOS)
        id: node-version-nix
        if: runner.os != 'Windows'
        run: echo "::set-output name=version::$(node -p 'require("./package.json").engines.node.match(/(\d.*)$/)[0]')"

      - name: Use Node.js ${{ steps.node-version-nix.outputs.version }} (Linux & macOS)
        if: runner.os != 'Windows'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node-version-nix.outputs.version }}

      - name: Get minimal Node.js version from package.json (Windows)
        id: node-version-win
        if: runner.os == 'Windows'
        run: echo "::set-output name=version::$(node -p 'require(\"./package.json\").engines.node.match(/(\d.*)$/)[0]')"

      - name: Use Node.js ${{ steps.node-version-win.outputs.version }} (Windows)
        if: runner.os == 'Windows'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node-version-win.outputs.version }}

      - name: Run tests for addon
        run: make test-tap

      - name: Upload prebuilds
        uses: actions/upload-artifact@v1
        with:
          name: addon-${{ runner.os }}
          path: prebuilds

  package:
    name: Build package
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Download macOS addon
        uses: actions/download-artifact@v1
        with:
          name: addon-macOS

      - name: Download Linux addon
        uses: actions/download-artifact@v1
        with:
          name: addon-Linux

      - name: Download Windows addon
        uses: actions/download-artifact@v1
        with:
          name: addon-Windows

      - name: Move addons to one folder
        run: mkdir prebuilds && mv ./addon-*/* ./prebuilds/

      - name: list
        run: find prebuilds

      - name: Build package
        run: make package

      - name: Get package version from package.json
        id: pkg-version
        run: echo "::set-output name=version::$(node -p 'require("./package.json").version')"

      - name: Upload package
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: secp256k1-${{ steps.pkg-version.outputs.version }}.tgz
